apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wwr6qia0n-nodejs
  janus-idp.io/tekton: wwr6qia0n-nodejs
  backstage.io/kubernetes-id: wwr6qia0n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wwr6qia0n-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
